### ISSUE TITLE
Show stats on current review load per person

### ISSUE THREAD

**Issue by wadlo** [review-vir/review-vir#8]
Sometimes we assign too many PRs to one team member to review. It would be nice if there was a feature that showed overall stats (or some other method) to make it more obvious who I should assign as primary for a new PR.

Perhaps displaying both:
- Open PRs that require their review
- Open PRs that they have already reviewed

It could be as a fraction: num_unreviewed_primary/total_reviewed_and_unreviewed

**Comment by electrovir** [comment]
included in latest update
